#define ACCELEROMETER_PIN_X 35
#define ACCELEROMETER_PIN_Y 32
#define ACCELEROMETER_PIN_Z 34

#define MOTION_SENSOR_PIN 17

#define CENTER_LED 4
#define RING_LED 14
#define GUN_RIGHT 0
#define GUN_LEFT 2
#define ROTATE_SERVO 22
#define WING_SERVO 19
#define WING_SWITCH 24

#define CENTER_ANGLE 90
#define STATIONARY_ANGLE 110
#define NUM_LEDS 