#define NUM_LEDS 8
#define CENTER_ANGLE 90
#define STATIONARY_ANGLE 110

#define FREQ 50           // one clock is 20 ms
#define FREQ_MINIMUM 205  // 1ms is 1/20, of 4096
#define FREQ_MAXIMUM 410  // 2ms is 2/20, of 4096

#define ACCELEROMETER_PIN_X 35
#define ACCELEROMETER_PIN_Y 32
#define ACCELEROMETER_PIN_Z 34

#define MOTION_SENSOR_PIN 17
#define CENTER_LED_PIN 4
#define RING_LED_PIN 14
#define LIGHTS_RIGHT_PIN 0
#define LIGHTS_LEFT_PIN 2
#define ROTATE_SERVO_PIN 22
#define WING_SERVO_PIN 19
#define WING_SWITCH_PIN 24